name: elvo-local-runtime

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  identity-db-data:
  wallet-db-data:
  billing-db-data:
  account-db-data:
  redis-data:
  rabbitmq-data:
  prometheus-data:
  grafana-data:
  alertmanager-data:
